### ISSUE TITLE
محاسبه محیط و مساحت اشکال هندسی 

### ISSUE THREAD

**Issue by koohgard** [SolmazHosseinlou/SimpleCalculator#1]
سلام خیلی خوب بود 
آفرین 
با استفاده از کلاس ها و اینترفیس ها  محیط و مساحت اشکال هندسی رو محاسبه کن لازم نیست فرم ویندوزی بنویسی کلاس ها و اینترفیس مورد نظر رو بنویسی کافیه

**Comment by koohgard** [comment]
برای انجام هر issue یه برنچ ایجاد می کنی و روی اون برنچ کار می کنی 
بعد که کارت تموم شد با پیام مناسب Commit می زنی
 و Merge request می دی

**Comment by SolmazHosseinlou** [comment]
سلام. وقت شما بخیر. یه ریپوزیتوری جدید درست کردم و فایل های پروژه رو اونجا قرار دادم. لطفا هر موقع وقت داشتید، یه نگاهی بهشون بندازید. برای بهتر شدنش هم اگر پیشنهادی داشتید، ممنون میشم بهم بگید.
@koohgard
